abstract final class AppRoutes {
  static const home = '/';
  static const imageToPdf = '/tools/image-to-pdf';
  static const imageEdit = '/tools/image-edit';
  static const scanToPdf = '/tools/scan-to-pdf';
  static const wordToPdf = '/tools/word-to-pdf';
  static const wordEdit = '/tools/word-edit';
  static const excelToPdf = '/tools/excel-to-pdf';
  static const excelEdit = '/tools/excel-edit';
  static const textToPdf = '/tools/text-to-pdf';
  static const textEdit = '/tools/text-edit';
  static const htmlToPdf = '/tools/html-to-pdf';
  static const htmlEdit = '/tools/html-edit';
  static const pptToPdf = '/tools/ppt-to-pdf';
  static const pptEdit = '/tools/ppt-edit';
  static const pdfToImage = '/tools/pdf-to-image';
  static const pdfToImageEdit = '/tools/pdf-to-image-edit';
  static const pdfProgress = '/tools/pdf-progress';
  static const pdfResult = '/tools/pdf-result';
}
